language: cpp

install:
  - cd ..
  - git clone -b master --depth 1 https://github.com/dknb0709/travis-test-project.git root
  - cd root
  - export ROOT="`pwd`"

script:
  - build-and-test.sh

notifications:
  email:
    false


