language: cpp

before-install:
  - sudo pip install codecov

install:
  - pwd
  - cd ..
  - git clone -b master --depth 1 https://github.com/dknb0709/travis-test-project.git root
  - ls root
  - cd root
  - export ROOT="`pwd`"

script:
  - ./build-and-test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    false


